const tempData = [
  {
    id: 'CM1',
    account: 'Wasif',
    phone: '0813908117',
    email: 'wasif@email.com',
    actions: 'unpaid',
  },
  {
    id: 'CM2',
    account: 'Wasif',
    phone: '0183908118',
    email: 'wasif@email.com',
    actions: 'unpaid',
  },
  {
    id: 'CM3',
    account: 'Wasif',
    phone: '0813908117',
    email: 'wasif@email.com',
    actions: 'unpaid',
  },
  {
    id: 'CM4',
    account: 'Wasif',
    phone: '0813908117',
    email: 'wasif@email.com',
    actions: 'unpaid',
  },
  {
    id: 'CM5',
    account: 'Wasif',
    phone: '0813908117',
    email: 'wasif@email.com',
    actions: 'unpaid',
  },
  {
    id: 'CM6',
    account: 'Wasif',
    phone: '0813908117',
    email: 'wasif@email.com',
    actions: 'unpaid',
  },
  {
    id: 'CM7',
    account: 'Wasif',
    phone: '0813908117',
    email: 'wasif@email.com',
    actions: 'unpaid',
  },
  {
    id: 'CM8',
    account: 'Wasif',
    phone: '0813908117',
    email: 'wasif@email.com',
    actions: 'unpaid',
  },
  {
    id: 'CM9',
    account: 'Wasif',
    phone: '0813908117',
    email: 'wasif@email.com',
    actions: 'unpaid',
  },
  {
    id: 'CM10',
    account: 'Wasif',
    phone: '0813908117',
    email: 'wasif@email.com',
    actions: 'unpaid',
  },
  {
    id: 'CM11',
    account: 'Wasif',
    phone: '0813908117',
    email: 'wasif@email.com',
    actions: 'unpaid',
  },
  {
    id: 'CM12',
    account: 'Wasif',
    phone: '0813908117',
    email: 'wasif@email.com',
    actions: 'unpaid',
  },
  {
    id: 'CM13',
    account: 'Wasif',
    phone: '0813908117',
    email: 'wasif@email.com',
    actions: 'unpaid',
  },
];

export default tempData;
